// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAhigz4Anx1vg93jltOUw2w14oImU2eVLg',
//     appId: '1:329897606722:web:0b15874ded6ae635d237db',
//     messagingSenderId: '329897606722',
//     projectId: 'peduli-lindungi-d0aad',
//     authDomain: 'peduli-lindungi-d0aad.firebaseapp.com',
//     databaseURL: 'https://peduli-lindungi-d0aad-default-rtdb.firebaseio.com',
//     storageBucket: 'peduli-lindungi-d0aad.appspot.com',
//     measurementId: 'G-V22P7X9WGX',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBKBvO8y7cw9WeVZObsuTWtvoUv0CFUBsI',
//     appId: '1:329897606722:android:8974e742b69e1461d237db',
//     messagingSenderId: '329897606722',
//     projectId: 'peduli-lindungi-d0aad',
//     databaseURL: 'https://peduli-lindungi-d0aad-default-rtdb.firebaseio.com',
//     storageBucket: 'peduli-lindungi-d0aad.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDh7lf-Kr7Nc-a8ebRYj8Cjfb2N15PGDPE',
//     appId: '1:329897606722:ios:d432f95605441826d237db',
//     messagingSenderId: '329897606722',
//     projectId: 'peduli-lindungi-d0aad',
//     databaseURL: 'https://peduli-lindungi-d0aad-default-rtdb.firebaseio.com',
//     storageBucket: 'peduli-lindungi-d0aad.appspot.com',
//     iosClientId: '329897606722-jou7bkkr164j1g5ij0qtqes03unbb157.apps.googleusercontent.com',
//     iosBundleId: 'com.example.pedulilindungiApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDh7lf-Kr7Nc-a8ebRYj8Cjfb2N15PGDPE',
//     appId: '1:329897606722:ios:d432f95605441826d237db',
//     messagingSenderId: '329897606722',
//     projectId: 'peduli-lindungi-d0aad',
//     databaseURL: 'https://peduli-lindungi-d0aad-default-rtdb.firebaseio.com',
//     storageBucket: 'peduli-lindungi-d0aad.appspot.com',
//     iosClientId: '329897606722-jou7bkkr164j1g5ij0qtqes03unbb157.apps.googleusercontent.com',
//     iosBundleId: 'com.example.pedulilindungiApp',
//   );
// }
